### ISSUE TITLE
Cannot define custom bantime per service

### ISSUE THREAD

**Issue by xiongchiamiov** [Oefenweb/ansible-fail2ban#16]
[The fail2ban manual](http://www.fail2ban.org/wiki/index.php/MANUAL_0_8#Jail_Options) says that `bantime` can be over-ridden in a jail.  You can define it in `fail2ban_services`, but it's just ignored when rendering `jail.local.j2`.

If you give me a week or two, I'd be glad to write and test a patch.

**Comment by tersmitten** [comment]
That would be nice. 

Is it possible that the fail2ban version is too old?

**Comment by xiongchiamiov** [comment]
I don't mean that fail2ban ignores the entry, but rather that this role never puts it in the config file in the first place.
