### ISSUE TITLE
fail2ban.conf should not be overwritten

### ISSUE THREAD

**Issue by j4m3s** [Oefenweb/ansible-fail2ban#26]
According to its docs, Fail2ban configuration should be done in .local files - the .conf files should never be modified:

> Every .conf file can be overridden with a file named .local. The .conf file is read first, then .local, with later settings overriding earlier ones. Thus, a .local file doesn't have to include everything in the corresponding .conf file, only those settings that you wish to override.
> Modifications should take place in the .local and not in the .conf. This avoids merging problem when upgrading. These files are well documented and detailed information should be available there.

(taken from http://www.fail2ban.org/wiki/index.php/MANUAL_0_8#Configuration)

The `fail2ban.conf.j2` file in this role should therefore be renamed `fail2ban.local.j2`, and deployed as `fail2ban.local` so as not to trample the package-default file.

**Comment by j4m3s** [comment]
(I'd also suggest removing the comments from the .local file - users should refer to the default file for the description of the valid values etc in case they change with a package update (as was the case for logging).

**Comment by tersmitten** [comment]
I like the change, but it's not really backwards compatible. Do you have any suggestions on fixing that?

**Comment by tersmitten** [comment]
@j4m3s Do you think this works in Ubuntu < 16.04?

**Comment by j4m3s** [comment]
I know it works in 14.04 - we only upgraded the servers to 16.04 a few months ago and have been using fail2ban like that for years.  I guess that means it must work in 12.04 too but I can't remember that far back :)

**Comment by tersmitten** [comment]
Thanks, I'll be merging you open pull requests soon :-)
