### ISSUE TITLE
Send mail with ansible

### ISSUE THREAD

**Issue by abandari2** [Oefenweb/ansible-fail2ban#30]
---
 - hosts: localhost

   tasks:
                                                                                                                                                    
     - name: sending mail

       mail:

           host: "smtp.gmail.com"

           port: 25

           username: "xxxxxxxx@gmail.com"

           password: "xxxxxxxxx"

           to: "xxxxxxxx@gmail.com"

           subject: "Ansible-report"

           body: "hai....."
-------------------------------------------------------------------------------------------------------------------------------

**The code is perfect!!!!!
For this im getting error:**

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [sending mail] ************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to send mail to server         smtp.gmail.com on port 587: [Errno 101] Network is unreachable", "rc": 1}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @email.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

How to configure this!!!! help me.....

**Comment by abandari2** [comment]
I have tried ports 25,465 and 587...........same error!!!!!!

**Comment by tersmitten** [comment]
I think you should ask this question in the Ansible Google Group. This Ansible role has nothing to do with the mail module.
