### ISSUE TITLE
Release v2.0.0

### ISSUE THREAD

**Issue by xiongchiamiov** [Oefenweb/ansible-fail2ban#34]
v2.0.0 [was tagged](https://github.com/Oefenweb/ansible-fail2ban/releases/tag/v2.0.0) 21 days ago, but it doesn't exist on Ansible Galaxy, which means it can't be installed.

**Comment by xiongchiamiov** [comment]
(Neither is v1.5.2, for that matter.)

**Comment by tersmitten** [comment]
There are some issues on galaxy with auto imports, I'll do a manual import now.

**Comment by tersmitten** [comment]
Done
